export const RSS_FEEDS = [
  { name: 'Le Monde Informatique', url: 'https://www.lemondeinformatique.fr/flux-rss.xml', theme: 'Optimisation du SI' },
  { name: 'Journal du Net', url: 'https://www.journaldunet.com/rss/', theme: 'Management et stratégie' },
  { name: 'ZDNet France', url: 'https://www.zdnet.fr/feeds/rss/actualites/', theme: 'Développement' },
  { name: 'The Hacker News', url: 'https://feeds.feedburner.com/TheHackersNews', theme: 'Cybersécurité' },
  { name: 'ANSSI', url: 'https://www.ssi.gouv.fr/feed/', theme: 'Cybersécurité' },
  { name: 'Krebs on Security', url: 'https://krebsonsecurity.com/feed/', theme: 'Cybersécurité' },
  { name: 'AWS Blog', url: 'https://aws.amazon.com/blogs/aws/feed/', theme: 'Cloud et virtualisation' },
  { name: 'InfoQ Cloud', url: 'https://feed.infoq.com/cloud', theme: 'Cloud et virtualisation' },
  { name: 'Anthropic Blog', url: 'https://www.anthropic.com/rss.xml', theme: 'Intelligence artificielle' },
  { name: 'MIT Technology Review AI', url: 'https://www.technologyreview.com/topic/artificial-intelligence/feed', theme: 'Intelligence artificielle' },
  { name: 'dev.to', url: 'https://dev.to/feed', theme: 'Développement' },
  { name: 'CSS Tricks', url: 'https://css-tricks.com/feed/', theme: 'Développement' },
  { name: 'Towards Data Science', url: 'https://towardsdatascience.com/feed', theme: 'Big Data' },
  { name: 'CoinTelegraph', url: 'https://cointelegraph.com/rss', theme: 'Blockchain' },
]

export const MOCK_ARTICLES = [
  {
    id: '1',
    title: 'Les entreprises françaises face aux nouvelles exigences NIS2',
    source: 'ANSSI',
    url: 'https://www.ssi.gouv.fr/',
    published_at: '2026-06-10T08:00:00Z',
    tags: ['Cybersécurité'],
    is_read: false,
    is_favorite: true,
    summary: null,
    key_points: null,
    note: '',
  },
  {
    id: '2',
    title: 'Claude 4 : Anthropic franchit un cap dans le raisonnement long',
    source: 'Anthropic Blog',
    url: 'https://www.anthropic.com/',
    published_at: '2026-06-09T14:30:00Z',
    tags: ['Intelligence artificielle'],
    is_read: false,
    is_favorite: false,
    summary: null,
    key_points: null,
    note: '',
  },
  {
    id: '3',
    title: 'AWS lance Bedrock Flows : orchestration d\'agents sans code',
    source: 'AWS Blog',
    url: 'https://aws.amazon.com/blogs/aws/',
    published_at: '2026-06-09T10:00:00Z',
    tags: ['Cloud et virtualisation', 'Intelligence artificielle'],
    is_read: true,
    is_favorite: false,
    summary: null,
    key_points: null,
    note: '',
  },
  {
    id: '4',
    title: 'Ransomware : record de rançons versées au premier semestre 2026',
    source: 'The Hacker News',
    url: 'https://feeds.feedburner.com/TheHackersNews',
    published_at: '2026-06-08T16:00:00Z',
    tags: ['Cybersécurité'],
    is_read: false,
    is_favorite: false,
    summary: null,
    key_points: null,
    note: '',
  },
  {
    id: '5',
    title: 'React 20 : les Server Components arrivent sur mobile avec Expo',
    source: 'dev.to',
    url: 'https://dev.to/',
    published_at: '2026-06-08T09:00:00Z',
    tags: ['Développement', 'Mobilité'],
    is_read: true,
    is_favorite: false,
    summary: 'React 20 apporte une intégration native des Server Components dans Expo, permettant aux développeurs mobile de bénéficier du rendu côté serveur sans compromettre l\'expérience native.',
    key_points: [
      'Les Server Components sont désormais supportés nativement dans Expo Router v4',
      'Réduction de 40% du bundle JS côté client grâce au déchargement des composants statiques',
      'Compatibilité maintenue avec les composants existants via une couche de transition automatique',
    ],
    note: 'À tester sur le projet Cairn dès que stable.',
  },
  {
    id: '6',
    title: 'Stratégie IA : pourquoi les DSI peinent à industrialiser les PoC',
    source: 'Journal du Net',
    url: 'https://www.journaldunet.com/',
    published_at: '2026-06-07T11:00:00Z',
    tags: ['Management et stratégie', 'Intelligence artificielle'],
    is_read: false,
    is_favorite: false,
    summary: null,
    key_points: null,
    note: '',
  },
  {
    id: '7',
    title: 'Kubernetes 1.32 : amélioration du scheduling GPU pour les workloads IA',
    source: 'InfoQ Cloud',
    url: 'https://feed.infoq.com/cloud',
    published_at: '2026-06-07T08:30:00Z',
    tags: ['Cloud et virtualisation', 'Big Data'],
    is_read: false,
    is_favorite: false,
    summary: null,
    key_points: null,
    note: '',
  },
  {
    id: '8',
    title: 'Ethereum : le passage au proof-of-stake réduit la consommation de 99,95%',
    source: 'CoinTelegraph',
    url: 'https://cointelegraph.com/',
    published_at: '2026-06-06T13:00:00Z',
    tags: ['Blockchain', 'SI et environnement'],
    is_read: true,
    is_favorite: false,
    summary: null,
    key_points: null,
    note: '',
  },
  {
    id: '9',
    title: 'CSS Grid subgrid : enfin supporté dans tous les navigateurs majeurs',
    source: 'CSS Tricks',
    url: 'https://css-tricks.com/',
    published_at: '2026-06-05T15:00:00Z',
    tags: ['Développement'],
    is_read: false,
    is_favorite: false,
    summary: null,
    key_points: null,
    note: '',
  },
  {
    id: '10',
    title: 'Data mesh : retour d\'expérience après 18 mois chez BNP Paribas',
    source: 'Towards Data Science',
    url: 'https://towardsdatascience.com/',
    published_at: '2026-06-05T09:00:00Z',
    tags: ['Big Data', 'Management et stratégie'],
    is_read: false,
    is_favorite: false,
    summary: null,
    key_points: null,
    note: '',
  },
]

// TODO: replace with real Supabase Edge Function call
// import supabase from './supabase'
// const { data } = await supabase.functions.invoke('fetch-rss')
export const fetchRssFeeds = async () => {
  return MOCK_ARTICLES
}
